;;; ars-jetbrains-dark-theme.el --- Personal JetBrains Dark theme -*- lexical-binding: t; -*-

;; Based on JetBrains Dark from:
;; https://github.com/artemevsevev/zed-theme-jetbrains

(deftheme ars-jetbrains-dark
  "Personal dark theme based on JetBrains Dark for Zed.")

(let ((bg "#1e1f22")
      (bg-alt "#26282d")
      (surface "#2b2d30")
      (surface-alt "#393b41")
      (surface-active "#494a4d")
      (selection "#214283")
      (selection-alt "#2e436e")
      (fg "#bcbec4")
      (fg-alt "#dfe1e5")
      (muted "#7a7e85")
      (muted-alt "#6f737a")
      (border "#393b41")
      (accent "#3474f0")
      (accent-alt "#467ff2")
      (blue "#6aa2d7")
      (blue-alt "#57aaf7")
      (cyan "#2aacb8")
      (cyan-alt "#47ccbd")
      (green "#6aab73")
      (green-alt "#57965d")
      (yellow "#d5a563")
      (yellow-alt "#f2c55c")
      (orange "#cf8e6d")
      (purple "#c77dbb")
      (violet "#8d91dc")
      (rose "#e59eae")
      (red "#fa6675")
      (red-alt "#f75464")
      (doc-green "#5f826b")
      (line-number "#4b5059")
      (line-number-active "#a1a3ab")
      (search "#114957")
      (paren "#2d543f")
      (added-bg "#253627")
      (removed-bg "#402929")
      (changed-bg "#25324d")
      (warning-bg "#665014")
      (ansi-black "#000000")
      (ansi-bright-black "#4e5157")
      (ansi-white "#ced0d6"))
  (custom-theme-set-faces
   'ars-jetbrains-dark
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,ansi-white))))
   `(fringe ((t (:background ,bg :foreground ,muted-alt))))
   `(highlight ((t (:background ,surface-alt))))
   `(hl-line ((t (:background ,bg-alt))))
   `(region ((t (:background ,selection :foreground ,fg-alt))))
   `(secondary-selection ((t (:background ,selection-alt))))
   `(shadow ((t (:foreground ,muted))))
   `(minibuffer-prompt ((t (:foreground ,accent-alt :weight bold))))
   `(escape-glyph ((t (:foreground ,orange))))
   `(homoglyph ((t (:foreground ,orange))))
   `(link ((t (:foreground ,blue-alt :underline t))))
   `(link-visited ((t (:foreground ,purple :underline t))))
   `(button ((t (:inherit link))))
   `(success ((t (:foreground ,green-alt))))
   `(warning ((t (:foreground ,yellow-alt))))
   `(error ((t (:foreground ,red))))
   `(trailing-whitespace ((t (:background ,red))))

   `(line-number ((t (:background ,bg :foreground ,line-number))))
   `(line-number-current-line ((t (:background ,bg-alt :foreground ,line-number-active))))
   `(vertical-border ((t (:foreground ,border))))
   `(window-divider ((t (:foreground ,border))))
   `(window-divider-first-pixel ((t (:foreground ,border))))
   `(window-divider-last-pixel ((t (:foreground ,border))))

   `(mode-line ((t (:background ,surface-alt :foreground ,fg-alt
                                :box (:line-width -1 :color ,surface-active)))))
   `(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-inactive ((t (:background ,surface :foreground ,muted
                                         :box (:line-width -1 :color ,border)))))
   `(header-line ((t (:background ,surface :foreground ,fg-alt
                                  :box (:line-width -1 :color ,border)))))
   `(tab-bar ((t (:background ,surface :foreground ,fg))))
   `(tab-bar-tab ((t (:background ,bg :foreground ,fg-alt))))
   `(tab-bar-tab-inactive ((t (:background ,surface :foreground ,muted))))

   `(isearch ((t (:background ,accent :foreground "#ffffff" :weight bold))))
   `(isearch-fail ((t (:background ,removed-bg :foreground ,red))))
   `(lazy-highlight ((t (:background ,search :foreground ,fg-alt))))
   `(match ((t (:background ,search :foreground ,fg-alt))))
   `(show-paren-match ((t (:background ,paren :foreground ,fg-alt :weight bold))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,bg :weight bold))))

   `(font-lock-builtin-face ((t (:foreground ,orange))))
   `(font-lock-comment-face ((t (:foreground ,muted))))
   `(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-constant-face ((t (:foreground ,purple :slant italic))))
   `(font-lock-doc-face ((t (:foreground ,doc-green :slant italic))))
   `(font-lock-doc-markup-face ((t (:foreground ,yellow))))
   `(font-lock-function-name-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,orange))))
   `(font-lock-negation-char-face ((t (:foreground ,orange))))
   `(font-lock-number-face ((t (:foreground ,cyan))))
   `(font-lock-operator-face ((t (:foreground ,fg))))
   `(font-lock-preprocessor-face ((t (:foreground ,yellow))))
   `(font-lock-property-name-face ((t (:foreground ,purple))))
   `(font-lock-property-use-face ((t (:foreground ,purple))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,orange))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,yellow))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,violet))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   `(font-lock-variable-use-face ((t (:foreground ,fg))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))

   `(completions-common-part ((t (:foreground ,blue :weight bold))))
   `(completions-first-difference ((t (:foreground ,orange :weight bold))))
   `(completion-match-0 ((t (:foreground ,blue :weight bold))))
   `(completion-match-1 ((t (:foreground ,orange :weight bold))))
   `(completion-match-2 ((t (:foreground ,purple :weight bold))))
   `(completion-match-3 ((t (:foreground ,green :weight bold))))
   `(orderless-match-face-0 ((t (:foreground ,blue :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,orange :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,purple :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,green :weight bold))))

   `(company-tooltip ((t (:background ,surface :foreground ,fg))))
   `(company-tooltip-selection ((t (:background ,selection-alt :foreground ,fg-alt))))
   `(company-tooltip-common ((t (:foreground ,blue :weight bold))))
   `(company-tooltip-common-selection ((t (:foreground ,blue-alt :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,muted))))
   `(company-tooltip-annotation-selection ((t (:foreground ,fg-alt))))
   `(company-tooltip-search ((t (:background ,search :foreground ,fg-alt))))
   `(company-scrollbar-bg ((t (:background ,surface-alt))))
   `(company-scrollbar-fg ((t (:background ,muted-alt))))
   `(company-preview ((t (:background ,surface :foreground ,muted))))
   `(company-preview-common ((t (:foreground ,blue :weight bold))))

   `(vertico-current ((t (:background ,selection-alt :foreground ,fg-alt))))
   `(vertico-group-title ((t (:foreground ,yellow :weight bold))))
   `(vertico-group-separator ((t (:foreground ,border :strike-through t))))
   `(consult-file ((t (:foreground ,fg))))
   `(consult-line-number ((t (:foreground ,muted))))
   `(consult-preview-line ((t (:background ,surface-alt))))
   `(consult-preview-match ((t (:inherit match))))
   `(marginalia-documentation ((t (:foreground ,muted))))
   `(marginalia-key ((t (:foreground ,blue))))
   `(marginalia-string ((t (:foreground ,green))))
   `(marginalia-number ((t (:foreground ,cyan))))
   `(marginalia-true ((t (:foreground ,green-alt))))
   `(marginalia-false ((t (:foreground ,red))))
   `(marginalia-null ((t (:foreground ,muted-alt))))
   `(marginalia-modified ((t (:foreground ,yellow))))

   `(diff-header ((t (:background ,surface :foreground ,fg-alt))))
   `(diff-file-header ((t (:background ,surface-alt :foreground ,fg-alt :weight bold))))
   `(diff-hunk-header ((t (:background ,surface-alt :foreground ,blue))))
   `(diff-context ((t (:foreground ,fg))))
   `(diff-added ((t (:background ,added-bg :foreground ,green))))
   `(diff-removed ((t (:background ,removed-bg :foreground ,red-alt))))
   `(diff-changed ((t (:background ,changed-bg :foreground ,blue-alt))))
   `(diff-refine-added ((t (:background "#447152" :foreground ,fg-alt))))
   `(diff-refine-removed ((t (:background "#8f5247" :foreground ,fg-alt))))
   `(vc-added-state ((t (:foreground ,green-alt))))
   `(vc-edited-state ((t (:foreground ,blue-alt))))
   `(vc-removed-state ((t (:foreground ,red-alt))))
   `(git-gutter:added ((t (:foreground ,green-alt :background ,bg))))
   `(git-gutter:modified ((t (:foreground ,blue-alt :background ,bg))))
   `(git-gutter:deleted ((t (:foreground ,red-alt :background ,bg))))
   `(git-gutter-fr:added ((t (:foreground ,green-alt :background ,bg))))
   `(git-gutter-fr:modified ((t (:foreground ,blue-alt :background ,bg))))
   `(git-gutter-fr:deleted ((t (:foreground ,red-alt :background ,bg))))

   `(magit-section-heading ((t (:foreground ,blue :weight bold))))
   `(magit-branch-local ((t (:foreground ,blue))))
   `(magit-branch-remote ((t (:foreground ,green))))
   `(magit-tag ((t (:foreground ,yellow))))
   `(magit-hash ((t (:foreground ,muted))))
   `(magit-diff-file-heading ((t (:foreground ,fg-alt :weight bold))))
   `(magit-diff-hunk-heading ((t (:background ,surface-alt :foreground ,blue))))
   `(magit-diff-context ((t (:foreground ,fg))))
   `(magit-diff-context-highlight ((t (:background ,bg-alt :foreground ,fg))))
   `(magit-diff-added ((t (:background ,added-bg :foreground ,green))))
   `(magit-diff-added-highlight ((t (:background ,added-bg :foreground ,green :weight bold))))
   `(magit-diff-removed ((t (:background ,removed-bg :foreground ,red-alt))))
   `(magit-diff-removed-highlight ((t (:background ,removed-bg :foreground ,red-alt :weight bold))))
   `(magit-diffstat-added ((t (:foreground ,green-alt))))
   `(magit-diffstat-removed ((t (:foreground ,red-alt))))

   `(org-document-title ((t (:foreground ,fg-alt :weight bold :height 1.2))))
   `(org-document-info ((t (:foreground ,blue))))
   `(org-level-1 ((t (:foreground ,blue :weight bold :height 1.15))))
   `(org-level-2 ((t (:foreground ,purple :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,green :weight bold :height 1.05))))
   `(org-level-4 ((t (:foreground ,yellow :weight bold))))
   `(org-level-5 ((t (:foreground ,orange :weight bold))))
   `(org-level-6 ((t (:foreground ,cyan :weight bold))))
   `(org-level-7 ((t (:foreground ,rose :weight bold))))
   `(org-level-8 ((t (:foreground ,violet :weight bold))))
   `(org-block ((t (:background ,surface :foreground ,fg))))
   `(org-block-begin-line ((t (:background ,surface-alt :foreground ,muted))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-code ((t (:background ,surface :foreground ,yellow))))
   `(org-verbatim ((t (:background ,surface :foreground ,green))))
   `(org-quote ((t (:background ,surface :foreground ,doc-green :slant italic))))
   `(org-table ((t (:foreground ,cyan))))
   `(org-link ((t (:inherit link))))
   `(org-date ((t (:foreground ,blue-alt :underline t))))
   `(org-special-keyword ((t (:foreground ,muted))))
   `(org-meta-line ((t (:foreground ,muted))))
   `(org-hide ((t (:foreground ,bg))))
   `(org-indent ((t (:inherit org-hide))))
   `(org-checkbox ((t (:foreground ,blue :weight bold))))
   `(org-todo ((t (:foreground ,red :weight bold))))
   `(org-done ((t (:foreground ,green-alt :weight bold))))
   `(org-warning ((t (:foreground ,yellow-alt :weight bold))))
   `(org-agenda-date ((t (:foreground ,blue))))
   `(org-agenda-date-today ((t (:foreground ,blue-alt :weight bold))))
   `(org-agenda-date-weekend ((t (:foreground ,purple))))
   `(org-scheduled ((t (:foreground ,green))))
   `(org-scheduled-today ((t (:foreground ,green-alt :weight bold))))
   `(org-scheduled-previously ((t (:foreground ,orange))))
   `(org-upcoming-deadline ((t (:foreground ,yellow-alt))))
   `(org-deadline-announce ((t (:foreground ,red))))

   `(markdown-header-face-1 ((t (:foreground ,blue :weight bold :height 1.15))))
   `(markdown-header-face-2 ((t (:foreground ,purple :weight bold :height 1.1))))
   `(markdown-header-face-3 ((t (:foreground ,green :weight bold :height 1.05))))
   `(markdown-header-face-4 ((t (:foreground ,yellow :weight bold))))
   `(markdown-header-face-5 ((t (:foreground ,orange :weight bold))))
   `(markdown-header-face-6 ((t (:foreground ,cyan :weight bold))))
   `(markdown-code-face ((t (:background ,surface :foreground ,yellow))))
   `(markdown-pre-face ((t (:background ,surface :foreground ,fg))))
   `(markdown-blockquote-face ((t (:foreground ,doc-green :slant italic))))
   `(markdown-link-face ((t (:inherit link))))
   `(markdown-url-face ((t (:foreground ,blue-alt :underline t))))
   `(markdown-list-face ((t (:foreground ,orange))))
   `(markdown-bold-face ((t (:weight bold))))
   `(markdown-italic-face ((t (:slant italic))))

   `(rainbow-delimiters-depth-1-face ((t (:foreground ,fg))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,orange))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,blue))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,purple))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,green))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,cyan))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,yellow))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,rose))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,violet))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,red :weight bold))))
   `(hl-todo ((t (:foreground ,yellow-alt :weight bold))))

   `(solaire-default-face ((t (:background ,surface :foreground ,fg))))
   `(solaire-fringe-face ((t (:background ,surface :foreground ,muted-alt))))
   `(solaire-line-number-face ((t (:background ,surface :foreground ,line-number))))
   `(solaire-hl-line-face ((t (:background ,surface-alt))))
   `(solaire-region-face ((t (:background ,selection :foreground ,fg-alt))))
   `(solaire-mode-line-face ((t (:background ,surface-alt :foreground ,fg-alt
                                             :box (:line-width -1 :color ,surface-active)))))
   `(solaire-mode-line-active-face ((t (:inherit solaire-mode-line-face))))
   `(solaire-mode-line-inactive-face ((t (:background ,surface :foreground ,muted
                                                      :box (:line-width -1 :color ,border)))))
   `(solaire-header-line-face ((t (:background ,surface :foreground ,fg-alt
                                               :box (:line-width -1 :color ,border)))))

   `(ansi-color-black ((t (:foreground ,ansi-black :background ,ansi-black))))
   `(ansi-color-bright-black ((t (:foreground ,ansi-bright-black :background ,ansi-bright-black))))
   `(ansi-color-red ((t (:foreground ,red :background ,red))))
   `(ansi-color-green ((t (:foreground ,green :background ,green))))
   `(ansi-color-yellow ((t (:foreground ,yellow-alt :background ,yellow-alt))))
   `(ansi-color-blue ((t (:foreground ,blue-alt :background ,blue-alt))))
   `(ansi-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(ansi-color-cyan ((t (:foreground ,cyan-alt :background ,cyan-alt))))
   `(ansi-color-white ((t (:foreground ,ansi-white :background ,ansi-white))))
   `(term-color-black ((t (:foreground ,ansi-black :background ,ansi-black))))
   `(term-color-red ((t (:foreground ,red :background ,red))))
   `(term-color-green ((t (:foreground ,green :background ,green))))
   `(term-color-yellow ((t (:foreground ,yellow-alt :background ,yellow-alt))))
   `(term-color-blue ((t (:foreground ,blue-alt :background ,blue-alt))))
   `(term-color-magenta ((t (:foreground ,purple :background ,purple))))
   `(term-color-cyan ((t (:foreground ,cyan-alt :background ,cyan-alt))))
   `(term-color-white ((t (:foreground ,ansi-white :background ,ansi-white)))))

  (custom-theme-set-variables
   'ars-jetbrains-dark
   `(ansi-color-names-vector [,ansi-black ,red ,green ,yellow-alt
                                          ,blue-alt ,purple ,cyan-alt ,ansi-white])))

(provide-theme 'ars-jetbrains-dark)

;;; ars-jetbrains-dark-theme.el ends here
