;;; ars-jetbrains-light-theme.el --- Personal JetBrains Light theme -*- lexical-binding: t; -*-

;; Based on JetBrains Light from:
;; https://github.com/artemevsevev/zed-theme-jetbrains

(deftheme ars-jetbrains-light
  "Personal light theme based on JetBrains Light for Zed.")

(let ((bg "#ffffff")
      (bg-alt "#f5f8fe")
      (surface "#f7f8fa")
      (surface-alt "#f5f7f9")
      (surface-active "#dbdcde")
      (selection "#a6d2ff")
      (selection-alt "#dfe1e5")
      (fg "#080808")
      (fg-alt "#000000")
      (muted "#404040")
      (muted-alt "#818594")
      (border "#ebecf0")
      (accent "#3573f0")
      (accent-alt "#0033b3")
      (blue "#00627a")
      (blue-alt "#1c5dfe")
      (cyan "#008e8e")
      (cyan-alt "#02906d")
      (green "#067d17")
      (green-alt "#55a76a")
      (yellow "#9e880d")
      (yellow-alt "#f49810")
      (orange "#c27203")
      (purple "#871094")
      (violet "#835dda")
      (rose "#b309b3")
      (red "#ff0000")
      (red-alt "#ff8266")
      (type "#a04908")
      (comment "#8c8c8c")
      (line-number "#aeb3c2")
      (line-number-active "#767a8a")
      (search "#fcd47e")
      (match-bg "#ccccff")
      (added-bg "#e9f5e6")
      (removed-bg "#ffe8e8")
      (changed-bg "#edebfc")
      (ansi-black "#000000")
      (ansi-bright-black "#656565")
      (ansi-white "#929292"))
  (custom-theme-set-faces
   'ars-jetbrains-light
   `(default ((t (:background ,bg :foreground ,fg))))
   `(cursor ((t (:background ,fg-alt))))
   `(fringe ((t (:background ,bg :foreground ,muted-alt))))
   `(highlight ((t (:background ,selection-alt))))
   `(hl-line ((t (:background ,bg-alt))))
   `(region ((t (:background ,selection :foreground ,fg))))
   `(secondary-selection ((t (:background ,match-bg))))
   `(shadow ((t (:foreground ,muted-alt))))
   `(minibuffer-prompt ((t (:foreground ,accent :weight bold))))
   `(escape-glyph ((t (:foreground ,orange))))
   `(homoglyph ((t (:foreground ,orange))))
   `(link ((t (:foreground ,accent :underline t))))
   `(link-visited ((t (:foreground ,purple :underline t))))
   `(button ((t (:inherit link))))
   `(success ((t (:foreground ,green-alt))))
   `(warning ((t (:foreground ,yellow-alt))))
   `(error ((t (:foreground ,red))))
   `(trailing-whitespace ((t (:background ,red-alt))))

   `(line-number ((t (:background ,bg :foreground ,line-number))))
   `(line-number-current-line ((t (:background ,bg-alt :foreground ,line-number-active))))
   `(vertical-border ((t (:foreground ,border))))
   `(window-divider ((t (:foreground ,border))))
   `(window-divider-first-pixel ((t (:foreground ,border))))
   `(window-divider-last-pixel ((t (:foreground ,border))))

   `(mode-line ((t (:background ,selection-alt :foreground ,fg-alt
                                :box (:line-width -1 :color ,surface-active)))))
   `(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-inactive ((t (:background ,surface :foreground ,muted
                                         :box (:line-width -1 :color ,border)))))
   `(header-line ((t (:background ,surface :foreground ,fg-alt
                                  :box (:line-width -1 :color ,border)))))
   `(tab-bar ((t (:background ,surface :foreground ,fg))))
   `(tab-bar-tab ((t (:background ,bg :foreground ,fg-alt))))
   `(tab-bar-tab-inactive ((t (:background ,surface :foreground ,muted))))

   `(isearch ((t (:background ,search :foreground ,fg-alt :weight bold))))
   `(isearch-fail ((t (:background ,removed-bg :foreground ,red))))
   `(lazy-highlight ((t (:background ,match-bg :foreground ,fg))))
   `(match ((t (:background ,match-bg :foreground ,fg))))
   `(show-paren-match ((t (:background ,match-bg :foreground ,fg-alt :weight bold))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,bg :weight bold))))

   `(font-lock-builtin-face ((t (:foreground ,accent-alt))))
   `(font-lock-comment-face ((t (:foreground ,comment :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-constant-face ((t (:foreground ,purple :slant italic))))
   `(font-lock-doc-face ((t (:foreground ,comment :slant italic))))
   `(font-lock-doc-markup-face ((t (:foreground ,yellow))))
   `(font-lock-function-name-face ((t (:foreground ,blue))))
   `(font-lock-keyword-face ((t (:foreground ,accent-alt))))
   `(font-lock-negation-char-face ((t (:foreground ,accent-alt))))
   `(font-lock-number-face ((t (:foreground ,blue-alt))))
   `(font-lock-operator-face ((t (:foreground ,fg))))
   `(font-lock-preprocessor-face ((t (:foreground ,yellow))))
   `(font-lock-property-name-face ((t (:foreground ,purple))))
   `(font-lock-property-use-face ((t (:foreground ,purple))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,accent-alt))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,yellow))))
   `(font-lock-string-face ((t (:foreground ,green))))
   `(font-lock-type-face ((t (:foreground ,type))))
   `(font-lock-variable-name-face ((t (:foreground ,fg-alt))))
   `(font-lock-variable-use-face ((t (:foreground ,fg-alt))))
   `(font-lock-warning-face ((t (:foreground ,red :weight bold))))

   `(completions-common-part ((t (:foreground ,blue :weight bold))))
   `(completions-first-difference ((t (:foreground ,accent-alt :weight bold))))
   `(completion-match-0 ((t (:foreground ,blue :weight bold))))
   `(completion-match-1 ((t (:foreground ,accent-alt :weight bold))))
   `(completion-match-2 ((t (:foreground ,purple :weight bold))))
   `(completion-match-3 ((t (:foreground ,green :weight bold))))
   `(orderless-match-face-0 ((t (:foreground ,blue :weight bold))))
   `(orderless-match-face-1 ((t (:foreground ,accent-alt :weight bold))))
   `(orderless-match-face-2 ((t (:foreground ,purple :weight bold))))
   `(orderless-match-face-3 ((t (:foreground ,green :weight bold))))

   `(company-tooltip ((t (:background ,surface :foreground ,fg))))
   `(company-tooltip-selection ((t (:background ,selection-alt :foreground ,fg-alt))))
   `(company-tooltip-common ((t (:foreground ,blue :weight bold))))
   `(company-tooltip-common-selection ((t (:foreground ,accent :weight bold))))
   `(company-tooltip-annotation ((t (:foreground ,muted))))
   `(company-tooltip-annotation-selection ((t (:foreground ,fg-alt))))
   `(company-tooltip-search ((t (:background ,match-bg :foreground ,fg))))
   `(company-scrollbar-bg ((t (:background ,surface-active))))
   `(company-scrollbar-fg ((t (:background ,muted-alt))))
   `(company-preview ((t (:background ,surface :foreground ,muted))))
   `(company-preview-common ((t (:foreground ,blue :weight bold))))

   `(vertico-current ((t (:background ,selection-alt :foreground ,fg-alt))))
   `(vertico-group-title ((t (:foreground ,yellow :weight bold))))
   `(vertico-group-separator ((t (:foreground ,border :strike-through t))))
   `(consult-file ((t (:foreground ,fg))))
   `(consult-line-number ((t (:foreground ,muted-alt))))
   `(consult-preview-line ((t (:background ,bg-alt))))
   `(consult-preview-match ((t (:inherit match))))
   `(marginalia-documentation ((t (:foreground ,muted))))
   `(marginalia-key ((t (:foreground ,blue))))
   `(marginalia-string ((t (:foreground ,green))))
   `(marginalia-number ((t (:foreground ,blue-alt))))
   `(marginalia-true ((t (:foreground ,green-alt))))
   `(marginalia-false ((t (:foreground ,red))))
   `(marginalia-null ((t (:foreground ,muted-alt))))
   `(marginalia-modified ((t (:foreground ,yellow-alt))))

   `(diff-header ((t (:background ,surface :foreground ,fg-alt))))
   `(diff-file-header ((t (:background ,selection-alt :foreground ,fg-alt :weight bold))))
   `(diff-hunk-header ((t (:background ,surface-active :foreground ,blue))))
   `(diff-context ((t (:foreground ,fg))))
   `(diff-added ((t (:background ,added-bg :foreground ,green))))
   `(diff-removed ((t (:background ,removed-bg :foreground ,red))))
   `(diff-changed ((t (:background ,changed-bg :foreground ,blue-alt))))
   `(diff-refine-added ((t (:background "#aadeaa" :foreground ,fg-alt))))
   `(diff-refine-removed ((t (:background "#ffc8bd" :foreground ,fg-alt))))
   `(vc-added-state ((t (:foreground ,green-alt))))
   `(vc-edited-state ((t (:foreground ,blue-alt))))
   `(vc-removed-state ((t (:foreground ,red))))
   `(git-gutter:added ((t (:foreground ,green-alt :background ,bg))))
   `(git-gutter:modified ((t (:foreground ,blue-alt :background ,bg))))
   `(git-gutter:deleted ((t (:foreground ,red-alt :background ,bg))))
   `(git-gutter-fr:added ((t (:foreground ,green-alt :background ,bg))))
   `(git-gutter-fr:modified ((t (:foreground ,blue-alt :background ,bg))))
   `(git-gutter-fr:deleted ((t (:foreground ,red-alt :background ,bg))))

   `(magit-section-heading ((t (:foreground ,blue :weight bold))))
   `(magit-branch-local ((t (:foreground ,blue))))
   `(magit-branch-remote ((t (:foreground ,green))))
   `(magit-tag ((t (:foreground ,yellow))))
   `(magit-hash ((t (:foreground ,muted-alt))))
   `(magit-diff-file-heading ((t (:foreground ,fg-alt :weight bold))))
   `(magit-diff-hunk-heading ((t (:background ,surface-active :foreground ,blue))))
   `(magit-diff-context ((t (:foreground ,fg))))
   `(magit-diff-context-highlight ((t (:background ,bg-alt :foreground ,fg))))
   `(magit-diff-added ((t (:background ,added-bg :foreground ,green))))
   `(magit-diff-added-highlight ((t (:background ,added-bg :foreground ,green :weight bold))))
   `(magit-diff-removed ((t (:background ,removed-bg :foreground ,red))))
   `(magit-diff-removed-highlight ((t (:background ,removed-bg :foreground ,red :weight bold))))
   `(magit-diffstat-added ((t (:foreground ,green-alt))))
   `(magit-diffstat-removed ((t (:foreground ,red))))

   `(org-document-title ((t (:foreground ,fg-alt :weight bold :height 1.2))))
   `(org-document-info ((t (:foreground ,blue))))
   `(org-level-1 ((t (:foreground ,blue :weight bold :height 1.15))))
   `(org-level-2 ((t (:foreground ,purple :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,green :weight bold :height 1.05))))
   `(org-level-4 ((t (:foreground ,yellow :weight bold))))
   `(org-level-5 ((t (:foreground ,orange :weight bold))))
   `(org-level-6 ((t (:foreground ,cyan :weight bold))))
   `(org-level-7 ((t (:foreground ,rose :weight bold))))
   `(org-level-8 ((t (:foreground ,violet :weight bold))))
   `(org-block ((t (:background ,surface :foreground ,fg))))
   `(org-block-begin-line ((t (:background ,selection-alt :foreground ,muted))))
   `(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-code ((t (:background ,surface :foreground ,yellow))))
   `(org-verbatim ((t (:background ,surface :foreground ,green))))
   `(org-quote ((t (:background ,surface :foreground ,comment :slant italic))))
   `(org-table ((t (:foreground ,cyan))))
   `(org-link ((t (:inherit link))))
   `(org-date ((t (:foreground ,accent :underline t))))
   `(org-special-keyword ((t (:foreground ,muted))))
   `(org-meta-line ((t (:foreground ,muted))))
   `(org-hide ((t (:foreground ,bg))))
   `(org-indent ((t (:inherit org-hide))))
   `(org-checkbox ((t (:foreground ,blue :weight bold))))
   `(org-todo ((t (:foreground ,red :weight bold))))
   `(org-done ((t (:foreground ,green-alt :weight bold))))
   `(org-warning ((t (:foreground ,yellow-alt :weight bold))))
   `(org-agenda-date ((t (:foreground ,blue))))
   `(org-agenda-date-today ((t (:foreground ,accent :weight bold))))
   `(org-agenda-date-weekend ((t (:foreground ,purple))))
   `(org-scheduled ((t (:foreground ,green))))
   `(org-scheduled-today ((t (:foreground ,green-alt :weight bold))))
   `(org-scheduled-previously ((t (:foreground ,orange))))
   `(org-upcoming-deadline ((t (:foreground ,yellow-alt))))
   `(org-deadline-announce ((t (:foreground ,red))))

   `(markdown-header-face-1 ((t (:foreground ,blue :weight bold :height 1.15))))
   `(markdown-header-face-2 ((t (:foreground ,purple :weight bold :height 1.1))))
   `(markdown-header-face-3 ((t (:foreground ,green :weight bold :height 1.05))))
   `(markdown-header-face-4 ((t (:foreground ,yellow :weight bold))))
   `(markdown-header-face-5 ((t (:foreground ,orange :weight bold))))
   `(markdown-header-face-6 ((t (:foreground ,cyan :weight bold))))
   `(markdown-code-face ((t (:background ,surface :foreground ,yellow))))
   `(markdown-pre-face ((t (:background ,surface :foreground ,fg))))
   `(markdown-blockquote-face ((t (:foreground ,comment :slant italic))))
   `(markdown-link-face ((t (:inherit link))))
   `(markdown-url-face ((t (:foreground ,accent :underline t))))
   `(markdown-list-face ((t (:foreground ,orange))))
   `(markdown-bold-face ((t (:weight bold))))
   `(markdown-italic-face ((t (:slant italic))))

   `(rainbow-delimiters-depth-1-face ((t (:foreground ,fg))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground ,accent-alt))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground ,blue))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground ,purple))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground ,green))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground ,blue-alt))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground ,yellow))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground ,rose))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground ,violet))))
   `(rainbow-delimiters-unmatched-face ((t (:foreground ,red :weight bold))))
   `(hl-todo ((t (:foreground ,yellow-alt :weight bold))))

   `(solaire-default-face ((t (:background ,surface :foreground ,fg))))
   `(solaire-fringe-face ((t (:background ,surface :foreground ,muted-alt))))
   `(solaire-line-number-face ((t (:background ,surface :foreground ,line-number))))
   `(solaire-hl-line-face ((t (:background ,selection-alt))))
   `(solaire-region-face ((t (:background ,selection :foreground ,fg))))
   `(solaire-mode-line-face ((t (:background ,selection-alt :foreground ,fg-alt
                                             :box (:line-width -1 :color ,surface-active)))))
   `(solaire-mode-line-active-face ((t (:inherit solaire-mode-line-face))))
   `(solaire-mode-line-inactive-face ((t (:background ,surface :foreground ,muted
                                                      :box (:line-width -1 :color ,border)))))
   `(solaire-header-line-face ((t (:background ,surface :foreground ,fg-alt
                                               :box (:line-width -1 :color ,border)))))

   `(ansi-color-black ((t (:foreground ,ansi-black :background ,ansi-black))))
   `(ansi-color-bright-black ((t (:foreground ,ansi-bright-black :background ,ansi-bright-black))))
   `(ansi-color-red ((t (:foreground ,red :background ,red))))
   `(ansi-color-green ((t (:foreground ,green :background ,green))))
   `(ansi-color-yellow ((t (:foreground ,yellow-alt :background ,yellow-alt))))
   `(ansi-color-blue ((t (:foreground ,blue-alt :background ,blue-alt))))
   `(ansi-color-magenta ((t (:foreground ,rose :background ,rose))))
   `(ansi-color-cyan ((t (:foreground ,cyan :background ,cyan))))
   `(ansi-color-white ((t (:foreground ,ansi-white :background ,ansi-white))))
   `(term-color-black ((t (:foreground ,ansi-black :background ,ansi-black))))
   `(term-color-red ((t (:foreground ,red :background ,red))))
   `(term-color-green ((t (:foreground ,green :background ,green))))
   `(term-color-yellow ((t (:foreground ,yellow-alt :background ,yellow-alt))))
   `(term-color-blue ((t (:foreground ,blue-alt :background ,blue-alt))))
   `(term-color-magenta ((t (:foreground ,rose :background ,rose))))
   `(term-color-cyan ((t (:foreground ,cyan :background ,cyan))))
   `(term-color-white ((t (:foreground ,ansi-white :background ,ansi-white)))))

  (custom-theme-set-variables
   'ars-jetbrains-light
   `(ansi-color-names-vector [,ansi-black ,red ,green ,yellow-alt
                                          ,blue-alt ,rose ,cyan ,ansi-white])))

(provide-theme 'ars-jetbrains-light)

;;; ars-jetbrains-light-theme.el ends here
